/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseCategory = IDL.Variant({
  'other' : IDL.Null,
  'arts' : IDL.Null,
  'technology' : IDL.Null,
  'business' : IDL.Null,
  'science' : IDL.Null,
});
export const CourseId = IDL.Nat;
export const LessonId = IDL.Nat;
export const Time = IDL.Int;
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'instructor' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'lessonIds' : IDL.Vec(LessonId),
  'category' : CourseCategory,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
  'courseId' : CourseId,
});
export const CourseWithProgress = IDL.Record({
  'completionPercentage' : IDL.Nat,
  'course' : Course,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func(
      [IDL.Text, IDL.Text, CourseCategory, IDL.Text],
      [CourseId],
      [],
    ),
  'createLesson' : IDL.Func(
      [CourseId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [LessonId],
      [],
    ),
  'deleteCourse' : IDL.Func([CourseId], [], []),
  'deleteLesson' : IDL.Func([LessonId], [], []),
  'enrollInCourse' : IDL.Func([CourseId], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getCourseCompletion' : IDL.Func([CourseId], [IDL.Nat], ['query']),
  'getCourseWithLessons' : IDL.Func(
      [CourseId],
      [IDL.Opt(IDL.Tuple(Course, IDL.Vec(Lesson)))],
      ['query'],
    ),
  'getCoursesByCategory' : IDL.Func(
      [CourseCategory],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getEnrolledCourses' : IDL.Func([], [IDL.Vec(CourseWithProgress)], ['query']),
  'getLesson' : IDL.Func([LessonId], [IDL.Opt(Lesson)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEnrolled' : IDL.Func([IDL.Principal, CourseId], [IDL.Bool], ['query']),
  'isLessonComplete' : IDL.Func(
      [IDL.Principal, LessonId],
      [IDL.Bool],
      ['query'],
    ),
  'markLessonComplete' : IDL.Func([LessonId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unenrollFromCourse' : IDL.Func([CourseId], [], []),
  'unmarkLessonComplete' : IDL.Func([LessonId], [], []),
  'updateCourse' : IDL.Func(
      [CourseId, IDL.Text, IDL.Text, CourseCategory, IDL.Text],
      [],
      [],
    ),
  'updateLesson' : IDL.Func(
      [LessonId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseCategory = IDL.Variant({
    'other' : IDL.Null,
    'arts' : IDL.Null,
    'technology' : IDL.Null,
    'business' : IDL.Null,
    'science' : IDL.Null,
  });
  const CourseId = IDL.Nat;
  const LessonId = IDL.Nat;
  const Time = IDL.Int;
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'instructor' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'lessonIds' : IDL.Vec(LessonId),
    'category' : CourseCategory,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
    'courseId' : CourseId,
  });
  const CourseWithProgress = IDL.Record({
    'completionPercentage' : IDL.Nat,
    'course' : Course,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func(
        [IDL.Text, IDL.Text, CourseCategory, IDL.Text],
        [CourseId],
        [],
      ),
    'createLesson' : IDL.Func(
        [CourseId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [LessonId],
        [],
      ),
    'deleteCourse' : IDL.Func([CourseId], [], []),
    'deleteLesson' : IDL.Func([LessonId], [], []),
    'enrollInCourse' : IDL.Func([CourseId], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getCourseCompletion' : IDL.Func([CourseId], [IDL.Nat], ['query']),
    'getCourseWithLessons' : IDL.Func(
        [CourseId],
        [IDL.Opt(IDL.Tuple(Course, IDL.Vec(Lesson)))],
        ['query'],
      ),
    'getCoursesByCategory' : IDL.Func(
        [CourseCategory],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getEnrolledCourses' : IDL.Func(
        [],
        [IDL.Vec(CourseWithProgress)],
        ['query'],
      ),
    'getLesson' : IDL.Func([LessonId], [IDL.Opt(Lesson)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEnrolled' : IDL.Func([IDL.Principal, CourseId], [IDL.Bool], ['query']),
    'isLessonComplete' : IDL.Func(
        [IDL.Principal, LessonId],
        [IDL.Bool],
        ['query'],
      ),
    'markLessonComplete' : IDL.Func([LessonId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unenrollFromCourse' : IDL.Func([CourseId], [], []),
    'unmarkLessonComplete' : IDL.Func([LessonId], [], []),
    'updateCourse' : IDL.Func(
        [CourseId, IDL.Text, IDL.Text, CourseCategory, IDL.Text],
        [],
        [],
      ),
    'updateLesson' : IDL.Func(
        [LessonId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };