/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : CourseId,
  'title' : string,
  'thumbnailUrl' : string,
  'instructor' : Principal,
  'createdAt' : Time,
  'description' : string,
  'lessonIds' : Array<LessonId>,
  'category' : CourseCategory,
}
export type CourseCategory = { 'other' : null } |
  { 'arts' : null } |
  { 'technology' : null } |
  { 'business' : null } |
  { 'science' : null };
export type CourseId = bigint;
export interface CourseWithProgress {
  'completionPercentage' : bigint,
  'course' : Course,
}
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'durationMinutes' : bigint,
  'videoUrl' : [] | [string],
  'courseId' : CourseId,
}
export type LessonId = bigint;
export type Time = bigint;
export interface UserProfile { 'bio' : string, 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<
    [string, string, CourseCategory, string],
    CourseId
  >,
  'createLesson' : ActorMethod<
    [CourseId, string, string, [] | [string], bigint, bigint],
    LessonId
  >,
  'deleteCourse' : ActorMethod<[CourseId], undefined>,
  'deleteLesson' : ActorMethod<[LessonId], undefined>,
  'enrollInCourse' : ActorMethod<[CourseId], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getCourseCompletion' : ActorMethod<[CourseId], bigint>,
  'getCourseWithLessons' : ActorMethod<
    [CourseId],
    [] | [[Course, Array<Lesson>]]
  >,
  'getCoursesByCategory' : ActorMethod<[CourseCategory], Array<Course>>,
  'getEnrolledCourses' : ActorMethod<[], Array<CourseWithProgress>>,
  'getLesson' : ActorMethod<[LessonId], [] | [Lesson]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEnrolled' : ActorMethod<[Principal, CourseId], boolean>,
  'isLessonComplete' : ActorMethod<[Principal, LessonId], boolean>,
  'markLessonComplete' : ActorMethod<[LessonId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unenrollFromCourse' : ActorMethod<[CourseId], undefined>,
  'unmarkLessonComplete' : ActorMethod<[LessonId], undefined>,
  'updateCourse' : ActorMethod<
    [CourseId, string, string, CourseCategory, string],
    undefined
  >,
  'updateLesson' : ActorMethod<
    [LessonId, string, string, [] | [string], bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];